apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    {{- toYaml .Values.mongo.data.resources | nindent 4 }}