apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    {{- include "labels" . | nindent 4 }}
  type: ClusterIP
