apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb
      containers:
        - name: mongodb
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag | default "latest" }}"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  serviceName: mongodb
  updateStrategy:
    type: RollingUpdate
