mongo:
  image:
    repository: mongo
    tag: "6.0.5"

  resources:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 4Gi

  data:
    resources:
      requests:
        storage: 64Gi